setwd("C:/Users/nvarshney/Desktop/R programming/Coursera/Git Hub and Programming assignments/Course10/Week 1/en_US")
library(tm)
library(qdap)
library(wordcloud)
library(R.utils)
library(stringi)
library(NLP)
library(readtext)
library(quanteda)
install.packages(c("ggplot2", "e1701", "caret", "irlba", "randomForest"))
library(ggplot2)
blog <- readLines("en_US.blogs.txt",n = 5000, encoding= "UTF-8")
news <- readLines("en_US.news.txt", n= 5000, encoding = "UTF-8")
twitter <- readLines("en_US.twitter.txt", n = 5000, encoding = "UTF-8")
en_US <- c(blog, news,twitter)
all_en <- sent_detect(en_US, language = "en", model = NULL)
head(en_US, 3)
corpus <- VectorSource(en_USall)
corpus <- VCorpus(corpus)
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
bad_words <- VectorSource(readLines("bad_words.txt"))
corpus <- tm_map(corpus, removeWords, bad_words)
corpus <- tm_map(corpus, stripWhitespace)
corpus <- tm_map(corpus, removeWords, stopwords("english"))
library(SnowballC)
corpus <- tm_map(corpus, stemDocument)
wordcloud(corpus, min.freq = 2,  scale=c(7,0.5),colors=brewer.pal(8, "Dark2"),  random.color= TRUE, random.order = FALSE, max.words = 500)
fulldata<-data.frame(text=unlist(sapply(corpus, `[`, "content")), stringsAsFactors=F)
fulldata[1:5,1]
dtm <- DocumentTermMatrix(corpus)
freq <- colSums(as.matrix(dtm))
#head(freq, 3)
#dtm
#dtm2 <- as.matrix(dtm)
#str(dtm2)
#frequency <- colSums(dtm2)
#str(frequency)

#library(quanteda)
#text_token <- tokens(en_US, what = "word", remove_numbers = TRUE, remove_punct = TRUE,
                     #remove_symbols = TRUE,
                    # remove_hyphens = TRUE)
#as.character(text_token[[457]])

#text_token <- tokens_tolower(text_token)
#text_token <- tokens_select(text_token, stopwords(), selection = "remove")
#text_token <- tokens_wordstem(text_token, language = "english")
#text_token <- dfm(text_token, tolower = FALSE)
#text_token_matrix <- as.matrix(text_token)
#dim(text_token_matrix)
#str(text_token_matrix)
#frequency <- colSums(text_token_matrix)
#frequency <- sort(frequency, decreasing = TRUE)
#frequency
#library(wordcloud)
#words <- names(frequency)
#table(wordcloud(words[1:200], frequency[1:200]))
#warning()
